# apiVersion: v1
# kind: Service
# metadata:
#   name: fetch-service
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 3000
#       # nodePort: 30008
#       protocol: TCP
#       name: http
#   selector:
#     app: fetch
apiVersion: v1
kind: Service
metadata:
  name: fetch-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30008
      # protocol: TCP
      # name: http
  selector:
    app: fetch
